modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Silentine/GrimoireOfGaia/issues"
license="Assets: ARR, Code: Creative Commons 0"

[[mods]]
modId="grimoireofgaia"
version="${file.jarVersion}"
displayName="Grimoire of Gaia 4"
displayURL="https://www.curseforge.com/minecraft/mc-mods/grimoire-of-gaia"
authors="Silentine, Mrbysco"
description='''
Adds mobs, monsters and monster girls.
'''
credits="Made possible by the combined effort of [bloodmc], [DoctorWiggles], [P3pp3rF1y] and [mrbysco] porting this mod to 1.12.2."
logoFile="logo.png"

[[dependencies.grimoireofgaia]]
modId="forge"
mandatory=true
versionRange="[40.1.16,)"
ordering="NONE"
side="BOTH"